CREATE TABLE IF NOT EXISTS public.daily_stock_stats
(
    symbol character varying(10) COLLATE pg_catalog."default",
    dt character varying(10) COLLATE pg_catalog."default",
    start_dt character varying(10) COLLATE pg_catalog."default",
    open real,
    high real,
    low real,
    close real,
    volume real,
    prev_open real,
    prev_high real,
    prev_low real,
    prev_close real,
    prev_volume real,
    roc020 real,
    roc125 real,
    rsi014 real,
    sma200 real,
    sma150 real,
    sma100 real,
    sma050 real,
    sma020 real,
    sma010 real,
    sma005 real,
    sma003 real,
    ema050 real,
    ema200 real,
    ema200pref real,
    sma200pref real,
    ema500pref real,
    sma50pref real,
    rsi14sctr real,
    ppo01sctr real,
    roc125sctr real,
    sctr1 real,
    sctr2 real,
    sctr3 real,
    sctr4 real,
    sctr5 real,
    sctr6 real,
    sctr7 real,
    sctr8 real,
    sctr9 real,
    sctr10 real,
    sctr11 real,
    sctr12 real,
    sctr13 real,
    sctr14 real,
    sctr15 real,
    sctr16 real,
    sctr17 real,
    sctr18 real,
    sctr19 real,
    sctr20 real,
    histday real,
    chg_pct_1d real,
    chg_pct_5d real,
    chg_pct_10d real,
    chg_pct_20d real,
    chg_pct_50d real,
    chg_pct_100d real,
    sma10turnover real,
    sma20turnover real,
    sma50turnover real,
    above_200d_sma real,
    above_150d_sma real,
    above_100d_sma real,
    above_50d_sma real,
    above_20d_sma real,
    above_10d_sma real,
    above_5d_sma real,
    industry character varying(50) COLLATE pg_catalog."default",
    sector character varying(50) COLLATE pg_catalog."default",
    short_name character varying(100) COLLATE pg_catalog."default",
    market_cap real,
    vp_high real,
    vp_low real,
    vp_bullish real,
    vp_bearish real,
    normalise_rs1 real,
    normalise_rs2 real,
    normalise_rs3 real,
    normalise_rs4 real,
    normalise_rs5 real,
    normalise_rs6 real,
    normalise_rs7 real,
    normalise_rs8 real,
    normalise_rs9 real,
    normalise_rs10 real,
    normalise_rs11 real,
    normalise_rs12 real,
    normalise_rs13 real,
    normalise_rs14 real,
    normalise_rs15 real,
    normalise_rs16 real,
    normalise_rs17 real,
    normalise_rs18 real,
    normalise_rs19 real,
    normalise_rs20 real,
    rs_priceoversma20 real,
    rs_slopesma20 real,
    rs_slopesma50 real,
    rs_slopesma150 real,
    priceoversma20 real,
    slopesma20 real,
    slopesma50 real,
    slopesma150 real,
    adr20 real,
    adr05 real,
    slopeadr20 real,
    slopeadr05 real
)

TABLESPACE pg_default;

ALTER TABLE public.daily_stock_stats
    OWNER to avnadmin;
